a = int(input("Enter The No. Of Rows: "))
for i in range(a):  # range(0, a)
    for j in range(a - i):  # range(0, a - i)
        print(" ", end="")
    c = chr(ord("A") + i)
    for k in range(i + 1):  # range(0, i + i)
        print(c, end="")
        c = chr(ord(c) - 1)
    print(end="\n")
